# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Apps/ALL_Labs/ENEL489Labs/Lab2/Lab2_Task2_IpCoreMult/Lab2_Task2_IpCoreMult.srcs/sources_1/ip/multi_core/multi_core.xci
# IP: The module: 'multi_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Apps/ALL_Labs/ENEL489Labs/Lab2/Lab2_Task2_IpCoreMult/Lab2_Task2_IpCoreMult.gen/sources_1/ip/multi_core/multi_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multi_core'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Apps/ALL_Labs/ENEL489Labs/Lab2/Lab2_Task2_IpCoreMult/Lab2_Task2_IpCoreMult.srcs/sources_1/ip/multi_core/multi_core.xci
# IP: The module: 'multi_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Apps/ALL_Labs/ENEL489Labs/Lab2/Lab2_Task2_IpCoreMult/Lab2_Task2_IpCoreMult.gen/sources_1/ip/multi_core/multi_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multi_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
