webtalk_init -webtalk_dir D:/Apps/ALL_Labs/ENEL489Labs/Lab2/Task2AfixpointAdderPlus/Task2AfixpointAdderPlus.sim/sim_1/behav/xsim/xsim.dir/FPAdder_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb 22 10:06:50 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b91beae8-5c43-41c2-9572-d2eb650e4153" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f5204d893f80430a8e9fcee9b49f6448" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3600X 6-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3793 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "120 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6468_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3355948063 -regid "" -xml D:/Apps/ALL_Labs/ENEL489Labs/Lab2/Task2AfixpointAdderPlus/Task2AfixpointAdderPlus.sim/sim_1/behav/xsim/xsim.dir/FPAdder_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Apps/ALL_Labs/ENEL489Labs/Lab2/Task2AfixpointAdderPlus/Task2AfixpointAdderPlus.sim/sim_1/behav/xsim/xsim.dir/FPAdder_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Apps/ALL_Labs/ENEL489Labs/Lab2/Task2AfixpointAdderPlus/Task2AfixpointAdderPlus.sim/sim_1/behav/xsim/xsim.dir/FPAdder_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
